### ISSUE TITLE
[ANDROID] Crash/Fatal Exception

### ISSUE THREAD

**Issue by VinniciusJesus** [alann-maulana/flutter_beacon#104]
**I'm getting a fatal exception when I monitor on android**
Flutter version: 2.2.3
Flutter_beacon: ^0.5.1
Samsung A10 - Android 10

**My Code**
` 
          await flutterBeacon.initializeScanning;
void start(List<Region> regions) {
    flutterBeacon.monitoring(regions).listen((MonitoringResult result) {
      print("monitoring");
    });
  }`

I get monitoring results for a few seconds before the app crashes.

```
E/AndroidRuntime(25271): FATAL EXCEPTION: pool-14-thread-3
E/AndroidRuntime(25271): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(25271): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(25271): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(25271): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(25271): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(25271): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(25271): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(25271): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(25271): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-14-thread-3
E/AndroidRuntime(25271): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1230)
E/AndroidRuntime(25271): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:862)
E/AndroidRuntime(25271): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime(25271): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:384)
E/AndroidRuntime(25271): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:176)
E/AndroidRuntime(25271): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:221)
E/AndroidRuntime(25271): 	at com.flutterbeacon.FlutterBeaconScanner$4.didDetermineStateForRegion(FlutterBeaconScanner.java:232)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.IntentHandler.convertIntentsToCallbacks(IntentHandler.java:73)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.service.Callback.call(Callback.java:76)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.service.MonitoringStatus.updateNewlyInsideInRegionsContaining(MonitoringStatus.java:136)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.service.ScanHelper.processBeaconFromScan(ScanHelper.java:347)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.service.ScanHelper.access$200(ScanHelper.java:63)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.service.ScanHelper$ScanProcessor.doInBackground(ScanHelper.java:435)
E/AndroidRuntime(25271): 	at org.altbeacon.beacon.service.ScanHelper$ScanProcessor.doInBackground(ScanHelper.java:401)
E/AndroidRuntime(25271): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(25271): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(25271): 	... 3 more
I/Process (25271): Sending signal. PID: 25271 SIG: 9
Lost connection to device.
```

**Comment by wayne900204** [comment]
i have this issue too

**Comment by Ahmadre** [comment]
@alann-maulana

**Comment by anthonyhunter** [comment]
see #101 for fix, PR waiting review

**Comment by Bhuvan69** [comment]
Is this issue fixed? I still face the same issue as mentioned above.

**Comment by VinniciusJesus** [comment]
> Is this issue fixed? I still face the same issue as mentioned above.

still unresolved

**Comment by EinatK** [comment]
any idea if and when this will be resolved ?

**Comment by HadenHiles** [comment]
Same issue here, spent the past few hours trying to find this thread. Was going crazy lol

**Comment by Guru-Zachw** [comment]
Temporary Solution:
```  
flutter_beacon:
    git: 
      url: https://github.com/alann-maulana/flutter_beacon.git
      ref: 0c63b2d8fb534d720c6430aabcd20704e87e69b0
```
