### ISSUE TITLE
No implementation found for method listen on channel flutter_beacon_event

### ISSUE THREAD

**Issue by mherfurt** [alann-maulana/flutter_beacon#106]
Hi all,
I am trying to use the flutter_beacon (0.5.1) package but do not succeed due to this message:

```
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel flutter_beacon_event:
MissingPluginException(No implementation found for method listen on channel flutter_beacon_event)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>
==========================================================================================

```
Did I forget about something, here?

The Platform I am trying to run this on is Android 11.
I am using flutter 2.5.1

    • Flutter version 2.5.1 at /home/xxx/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

Thanks for looking into this!

Cheers
Martin

**Comment by barangungor** [comment]
I'm facing same error, i should fix this error can you help me if you resolved this.

**Comment by mherfurt** [comment]
I resolved it by moving to a different package: beacons_plugin: ^2.0.1
No issues so far!

**Comment by barangungor** [comment]
I'll try, thanks.
