### ISSUE TITLE
Beacon Scanning not working when app is in background or terminated

### ISSUE THREAD

**Issue by ghost** [alann-maulana/flutter_beacon#129]
Not able to scan beacon when my app is in background as well as terminated. I am trying to call beacon scanning functionality in flutter using Background Service but beacon scanning is not working in service and getting Error. 

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel flutter_beacon_event:
MissingPluginException(No implementation found for method listen on channel flutter_beacon_event)

**Comment by Kreshnik** [comment]
@PriyankaInoid did you find a solution to this?

**Comment by AdnanAliChohan** [comment]
@PriyankaInoid @Kreshnik find any solution?

**Comment by Mitsutan** [comment]
I have same issue
``` shell
10-18 20:47:06.517 16843 16870 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isBroadcasting on channel flutter_beacon)
10-18 20:47:06.517 16843 16870 E flutter : #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
10-18 20:47:06.517 16843 16870 E flutter : <asynchronous suspension>
10-18 20:47:06.517 16843 16870 E flutter : #1      FlutterBeacon.isBroadcasting (package:flutter_beacon/flutter_beacon.dart:259)
10-18 20:47:06.517 16843 16870 E flutter : <asynchronous suspension>
10-18 20:47:06.517 16843 16870 E flutter : #2      BeaconFunc.stopBeacon (package:sysdev_suretti/utils/beacon.dart:182)
10-18 20:47:06.517 16843 16870 E flutter : <asynchronous suspension>
10-18 20:47:06.517 16843 16870 E flutter :
```

**Comment by ghost** [comment]
yes, I have found the solution. You have to use this library 'https://github.com/alann-maulana/flutter_beacon'  and handle all calculation related to becaon when app is in backeground in Android Native and IOS native using Platform Channel.

**Comment by Mitsutan** [comment]
> yes, I have found the solution. You have to use this library 'https://github.com/alann-maulana/flutter_beacon' and handle all calculation related to becaon when app is in backeground in Android Native and IOS native using Platform Channel.

ah…well…, Is that mean I need to learn kotlin and swift?
