### ISSUE TITLE
android-distance.json database not found

### ISSUE THREAD

**Issue by bakboem** [alann-maulana/flutter_beacon#136]
I'm not sure if it's related to https://github.com/AltBeacon/android-beacon-library/issues/967
this warning is really annoying..

W/DistanceConfigFetcher(14241): error reading beacon data
W/DistanceConfigFetcher(14241): java.io.FileNotFoundException: https://s3.amazonaws.com/android-beacon-library/android-distance.json
W/DistanceConfigFetcher(14241):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/DistanceConfigFetcher(14241):         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
W/DistanceConfigFetcher(14241):         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
W/DistanceConfigFetcher(14241):         at org.altbeacon.beacon.distance.DistanceConfigFetcher.request(DistanceConfigFetcher.java:94)
W/DistanceConfigFetcher(14241):         at org.altbeacon.beacon.distance.ModelSpecificDistanceUpdater.doInBackground(ModelSpecificDistanceUpdater.java:28)
W/DistanceConfigFetcher(14241):         at org.altbeacon.beacon.distance.ModelSpecificDistanceUpdater.doInBackground(ModelSpecificDistanceUpdater.java:16)
W/DistanceConfigFetcher(14241):         at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/DistanceConfigFetcher(14241):         at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/DistanceConfigFetcher(14241):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/DistanceConfigFetcher(14241):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/DistanceConfigFetcher(14241):         at java.lang.Thread.run(Thread.java:1012)
W/ModelSpecificDistanceCalculator(14241): Cannot updated distance models from online database at java.io.FileNotFoundException: https://s3.amazonaws.com/android-beacon-library/android-distance.json

**Comment by PlayCulture** [comment]
I've been working with this library for the last year or so and this feature has never worked. I assume the database it's trying to reach is not available anymore, however I've found the default settings to work just fine

**Comment by bakboem** [comment]
Yes. It's annoying. But it does not affect obtaining beacon signals

**Comment by MahmoudMagdyEllawatty** [comment]
how to solve this?
