### ISSUE TITLE
AndroidRuntimeException returned when Location is off

### ISSUE THREAD

**Issue by yarmenteros** [alann-maulana/flutter_beacon#81]
A **AndroidRuntimeException** is thrown when _ranging_ if Location permission is granted but it's off/disabled.

Android Version: 11
Device: One Plus 7
Plugin Version: 0.3.0

## Error Logs

E/MethodChannel#flutter_beacon(13574): Failed to handle method call
E/MethodChannel#flutter_beacon(13574): **android.util.AndroidRuntimeException**: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/MethodChannel#flutter_beacon(13574): 	at android.app.ContextImpl.startActivity(ContextImpl.java:964)
E/MethodChannel#flutter_beacon(13574): 	at android.app.ContextImpl.startActivity(ContextImpl.java:940)
E/MethodChannel#flutter_beacon(13574): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
E/MethodChannel#flutter_beacon(13574): 	at com.flutterbeacon.FlutterBeaconPlugin.openLocationSettings(FlutterBeaconPlugin.java:252)
E/MethodChannel#flutter_beacon(13574): 	at com.flutterbeacon.FlutterBeaconPlugin.initializeAndCheck(FlutterBeaconPlugin.java:232)
E/MethodChannel#flutter_beacon(13574): 	at com.flutterbeacon.FlutterBeaconPlugin.onMethodCall(FlutterBeaconPlugin.java:125)
E/MethodChannel#flutter_beacon(13574): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_beacon(13574): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_beacon(13574): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_beacon(13574): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_beacon(13574): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter_beacon(13574): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter_beacon(13574): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/MethodChannel#flutter_beacon(13574): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_beacon(13574): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#flutter_beacon(13574): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

## Workaround
Until this bug been fixed, my handler looks like

```java
      try {
        await flutterBeacon.initializeAndCheckScanning;
      } on PlatformException catch (e) {
        // hack: when bluetooth is on and location is off, plugin returns an unhandled exception.
        final locationStatus = await Permission.location.serviceStatus;
        if (!locationStatus.isEnabled) {
          /// TODO
        }
        /// TODO
      }
```

**Comment by azim92** [comment]
1) Open Android Module from your main project.
  `Project > Right Click > Flutter > Open Android module in Android Studio`
  ![Untitled](https://user-images.githubusercontent.com/30527495/108536076-f9104580-7316-11eb-9f5e-d90e4a0210cf.png)

2) Expand flutter_beacon and open FlutterBeaconPlugin.java
  ![Untitled2](https://user-images.githubusercontent.com/30527495/108536169-1513e700-7317-11eb-8042-b9fd1e925df9.png)

3) Replace the following function codes to the temporary solution below:
![Untitled3](https://user-images.githubusercontent.com/30527495/108536265-35dc3c80-7317-11eb-9049-ee3724aea225.png)


Original:
```java
  private void openLocationSettings() {
    Intent intent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
    registrar.context().startActivity(intent);
  }
```

Temporary Solution
```java
  private void openLocationSettings() {
    Intent intent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    registrar.context().startActivity(intent);
  }
```

You should be able to open the android's location setting on pressing the location off icon.

**Comment by alann-maulana** [comment]
Thanks for reporting, I will take a look of it soon.
